### ISSUE TITLE
Script fails due to syntax error.

### ISSUE THREAD

**Issue by DominicMe** [teeedubb/teeedubb-xbmc-repo#10]
I am running kodi on Arch Linux in standalone mode and got steam installed. Steam launches fine with [ startx /usr/bin/steam -bigpicture ].

Launching steam with the launcher from Kodi does nothing. Trying to launch the script manually with [ . steam-launch.sh "/usr/bin/steam" "/usr/bin/kodi" "1" "false" "false" "false" ] command results in the following errors:

bash: $'\r': command not found
bash: $'\r': command not found
bash: steam-launch.sh: line 16: syntax error near unexpected token `$'in\r''
'ash: steam-launch.sh: line 16: `case "$(uname -s)" in

Tried older version of the add-on with no change. What could be the issue?

**Comment by teeedubb** [comment]
Probably due to the windows line endings. New version has been uploaded, can you try with 3.1.4? Make sure you enable the 'delete and update user scripts' in the addon setting prior to running.

**Comment by DominicMe** [comment]
Yes, that's what I figured but wasn't sure because I used the script before on Linux and it worked. Will try later today, thanks!

**Comment by DominicMe** [comment]
Yes, that seems to have fixed this particular issue. However another issue emerged. I am running kodi uner it's own system user and that seems to cause an issue. If I run [ su -s /bin/bash -c '/var/lib/kodi/.kodi/userdata/addon_data/script.steam.launcher/scripts/steam-launch.sh "/usr/bin/steam" "/usr/bin/kodi" "1" "false" "false" "false"' kodi" ] it seems to start as normal in the terminal window as the log messages get printer as normal but nothing appears on screen. Any ideas what specifically might be the cause? It works fine if started as a standard user. Adding kodi user to wheel group didn't help.

**Comment by teeedubb** [comment]
Not sure why... does steam launch ok as the kodi user?

**Comment by DominicMe** [comment]
Kodi user is the system user so not it doesn't start. It works fine when the script is started with the standard admin user. Will do some more testing and get back.

**Comment by DominicMe** [comment]
Finally found what was causing the issue. It seem that steam was installed under different users home. Unfortunately installing under standalone kodi's home is ugly as it is under root owned directories. Not a usable situation for me.

Any chance you might add "run as user" option to the add-on? That would mean Steam could be started under a different user in it's own home.

**Comment by teeedubb** [comment]
That would require users to input a password or mess around with the sudoers file, no?
You can just create a pre-steam script start steam from that.

**Comment by DominicMe** [comment]
It probably does, yes.

If I run steam from the pre-steam script won't it just run twice? I didn't see a way to disable running the main steam script so I didn't consider this an option.

**Comment by teeedubb** [comment]
If steam is running the addon will either attempt to focus bpm or start bpm (though not sure if starting bpm via cli will start another steam instance), but you can just pint the addon to run /bin/false or another script that does nothing etc.. instead of steam

**Comment by DominicMe** [comment]
Looked into it a bit more and it seems there's an alternative to sudoers file when it comes to running as a specific user. I believe this sudo code should be enough to implement "run as user" feature:

$user = false;
$user = run-as-user;
if linux && if $user:
   chown $user:$user steam-launch.sh
   chmod 4755 steam-launcher.sh


chmod sets the SetUID and limited permissions. SetUID makes the script run as the owner. The only issue may be that it may require root to execute the script, though I am not sure.

**Comment by teeedubb** [comment]
Original issue has been resolved, closing this issue.
