### ISSUE TITLE
Unable to start steam / check error logs

### ISSUE THREAD

**Issue by ghost** [teeedubb/teeedubb-xbmc-repo#12]
I just installed steam on my ubuntu 17.10 x64 (htpc) and the plugin from superrepo. I configured to match the steam binary (/usr/games/steam), kodi (17.6) location was correct. I use lightdm as dm. wmctrl is installed.
is there anything known ? can i turn on debug infos for that plugin or do i have to turn on debug general in kodi? it just says "check kodi.log" but, there is no entry from that steam app in that log. The last log entry is from the CEC adapter

**Comment by blahmutz** [comment]
> 16:47:35.667 T:139793428240128   DEBUG: script.steam.launcher: ****Running Steam-Launcher v3.2.2....
> 16:47:35.667 T:139793428240128   DEBUG: script.steam.launcher: running on osAndroid, osOsx, osLinux, osWin: 0 0 1 0
> 16:47:35.667 T:139793428240128   DEBUG: script.steam.launcher: System text encoding in use: UTF-8
> 16:47:35.667 T:139793428240128   DEBUG: script.steam.launcher: usr scripts are set to be checked for updates...
> 16:47:35.667 T:139793428240128   DEBUG: script.steam.launcher: usr scripts are not set to be deleted, running version check
> 16:47:35.667 T:139793428240128   DEBUG: script.steam.launcher: sys "steam.launcher.script.revision=": 015
> 16:47:35.667 T:139793428240128   DEBUG: script.steam.launcher: usr "steam.launcher.script.revision=": 015
> 16:47:35.667 T:139793428240128   DEBUG: script.steam.launcher: userdata script are up to date
> 16:47:35.667 T:139793428240128   DEBUG: script.steam.launcher: skipping deleting userdata scripts, option disabled: delUserScriptSett = false
> 16:47:35.667 T:139793428240128   DEBUG: script.steam.launcher: script file already exists, skipping copy to userdata: /home/kodi/.kodi/userdata/addon_data/script.steam.launcher/scripts/steam-launch.sh
> 16:47:35.676 T:139793428240128   DEBUG: script.steam.launcher: wmctrl present, checking if a window manager is running...
> 16:47:35.681 T:139793428240128   DEBUG: script.steam.launcher: ERROR: A window manager is NOT running - unless you are using the SteamOS compositor Steam BPM needs a windows manager. If you are using the SteamOS compositor disable the addon option "Check for program wmctrl"
> 
So seems like its not working with lightdm - would be nice if it would work with lightdm, as i only use kodi at the moment, so no need for a fully blown desktop like kde etc.

**Comment by blahmutz** [comment]
i installed now fluxbox. when i start the htpc, it autologin the user kodi, the used session is fluxbox. in fluxbox, i have a startup entry on the user "kodi" to start /usr/bin/kodi &
when i try to start steam, nothing happens  :(

here is the log:

> 18:21:39.551 T:140552083314432    INFO: initializing python engine.
> 18:21:39.551 T:140552083314432   DEBUG: CPythonInvoker(10, /home/kodi/.kodi/addons/script.steam.launcher/default.py): start processing
> 18:21:39.560 T:140552227878656   DEBUG: CAddonDatabase::SetLastUsed[script.steam.launcher] took 10 ms
> 18:21:39.600 T:140552083314432   DEBUG: -->Python Interpreter Initialized<--
> 18:21:39.600 T:140552083314432   DEBUG: CPythonInvoker(10, /home/kodi/.kodi/addons/script.steam.launcher/default.py): the source file to load is "/home/kodi/.kodi/addons/script.steam.launcher/default.py"
> 18:21:39.600 T:140552083314432   DEBUG: CPythonInvoker(10, /home/kodi/.kodi/addons/script.steam.launcher/default.py): setting the Python path to /home/kodi/.kodi/addons/script.steam.launcher:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0
> 18:21:39.600 T:140552083314432   DEBUG: CPythonInvoker(10, /home/kodi/.kodi/addons/script.steam.launcher/default.py): entering source directory /home/kodi/.kodi/addons/script.steam.launcher
> 18:21:39.600 T:140552083314432   DEBUG: CPythonInvoker(10, /home/kodi/.kodi/addons/script.steam.launcher/default.py): instantiating addon using automatically obtained id of "script.steam.launcher" dependent on version 2.19.0 of the xbmc.python api
> 18:21:39.626 T:140552083314432   DEBUG: script.steam.launcher: ****Running Steam-Launcher v3.2.2....
> 18:21:39.626 T:140552083314432   DEBUG: script.steam.launcher: running on osAndroid, osOsx, osLinux, osWin: 0 0 1 0
> 18:21:39.626 T:140552083314432   DEBUG: script.steam.launcher: System text encoding in use: UTF-8
> 18:21:39.627 T:140552083314432   DEBUG: script.steam.launcher: usr scripts are set to be checked for updates...
> 18:21:39.627 T:140552083314432   DEBUG: script.steam.launcher: usr scripts are not set to be deleted, running version check
> 18:21:39.627 T:140552083314432   DEBUG: script.steam.launcher: sys "steam.launcher.script.revision=": 015
> 18:21:39.627 T:140552083314432   DEBUG: script.steam.launcher: usr "steam.launcher.script.revision=": 015
> 18:21:39.627 T:140552083314432   DEBUG: script.steam.launcher: userdata script are up to date
> 18:21:39.627 T:140552083314432   DEBUG: script.steam.launcher: skipping deleting userdata scripts, option disabled: delUserScriptSett = false
> 18:21:39.627 T:140552083314432   DEBUG: script.steam.launcher: script file already exists, skipping copy to userdata: /home/kodi/.kodi/userdata/addon_data/script.steam.launcher/scripts/steam-launch.sh
> 18:21:39.635 T:140552083314432   DEBUG: script.steam.launcher: wmctrl present, checking if a window manager is running...
> 18:21:39.640 T:140552083314432   DEBUG: script.steam.launcher: A window manager is running...
> 18:21:39.640 T:140552083314432   DEBUG: script.steam.launcher: running program file check, option is enabled: filePathCheck = true
> 18:21:39.640 T:140552083314432   DEBUG: script.steam.launcher: Steam executable exists /usr/games/steam
> 18:21:39.640 T:140552083314432   DEBUG: script.steam.launcher: Xbmc executable exists /usr/bin/kodi
> 18:21:39.640 T:140552083314432   DEBUG: script.steam.launcher: pre steam script: false
> 18:21:39.640 T:140552083314432   DEBUG: script.steam.launcher: post steam script: false
> 18:21:39.640 T:140552083314432   DEBUG: script.steam.launcher: quit setting: 2 selected, asking user to pick
> 18:21:39.643 T:140553807075712   DEBUG: ------ Window Init (DialogConfirm.xml) ------
> 18:21:42.194 T:140553807075712   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
> 18:21:42.194 T:140552083314432   DEBUG: script.steam.launcher: quit setting selected: 0
> 18:21:42.194 T:140552083314432   DEBUG: script.steam.launcher: attempting to launch: "/home/kodi/.kodi/userdata/addon_data/script.steam.launcher/scripts/steam-launch.sh" "/usr/games/steam" "/usr/bin/kodi" "0" "false" "false" "false"
> 18:21:42.195 T:140552083314432   DEBUG: "/home/kodi/.kodi/userdata/addon_data/script.steam.launcher/scripts/steam-launch.sh" "/usr/games/steam" "/usr/bin/kodi" "0" "false" "false" "false"
> 18:21:42.203 T:140552083314432   DEBUG: script.steam.launcher: busy dialog started
> 18:21:42.210 T:140553807075712   DEBUG: Activating window ID: 10138
> 18:21:42.210 T:140553807075712   DEBUG: ------ Window Init (DialogBusy.xml) ------
> 18:21:52.206 T:140552083314432   DEBUG: script.steam.launcher: busy dialog stopped after: 10 seconds
> 18:21:52.207 T:140552083314432    INFO: CPythonInvoker(10, /home/kodi/.kodi/addons/script.steam.launcher/default.py): script successfully run
> 18:21:52.225 T:140552083314432    INFO: Python script stopped
> 18:21:52.225 T:140552083314432   DEBUG: Thread LanguageInvoker 140552083314432 terminating
> 18:21:52.393 T:140553807075712   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
> 18:22:09.561 T:140552227878656   DEBUG: Thread JobWorker 140552227878656 terminating (autodelete)
> 18:22:09.561 T:140552219485952   DEBUG: Thread JobWorker 140552219485952 terminating (autodelete)

**Comment by blahmutz** [comment]
just tried that:
kodi@htpc:~$ /home/kodi/.kodi/userdata/addon_data/script.steam.launcher/scripts/steam-launch.sh /usr/games/steam /usr/bin/kodi 0 false false false
-su: /home/kodi/.kodi/userdata/addon_data/script.steam.launcher/scripts/steam-launch.sh: /bin/bash^M: **Defekter Interpreter: Datei oder Verzeichnis nicht gefunden**
kodi@htpc:~$ file /home/kodi/.kodi/userdata/addon_data/script.steam.launcher/scripts/steam-launch.sh
/home/kodi/.kodi/userdata/addon_data/script.steam.launcher/scripts/steam-launch.sh: Bourne-Again shell script, ASCII text executable, with CRLF line terminators

**Comment by blahmutz** [comment]
`sed -i -e 's/\r$//' /home/kodi/.kodi/userdata/addon_data/script.steam.launcher/scripts/steam-launch.sh`
resolved the problem

**Comment by ciaccom** [comment]
@blahmutz 👍 
Thx  a lot - i tried steam addon for kodi yesterday and it only started short according to the log file (10 seconds after busy dialog, then stopped). It did not stop kodi. Now with your hint with CRLF it's working! Great!

OffTopic: it's funny that you posted your solution yesterday, when i first tried it. Xmas :)

**Comment by blahmutz** [comment]
can you give me some more information what OS/wm you are running? i dont get it working with the bpm (big picture mode) that steam minimizes and the game starts. i always have to minimize steam by myself, go to the taskbar, open the game with a click (its not that problematic, i know, but it would be nice if it would work without, i *guess* its related to fluxbox as it does not support the complete ewhm protocol)

**Comment by ciaccom** [comment]
i didn't tried a game so long - just wanted to test, if the kodi steam addon is working. 

here it is ubuntu trusty/14.04.5 (server-image) running (with kernel 4.14.5-041405-generic #201712101332). As WindowManager it is "openbox". The steam addon only starts, if "wmctrl" is disabled under the advanced settings (it does not determine the WM itself - against the hint for linux users). System is amd64 with the needed i386-libs installed necessary for the steam client.

I will try a game now, maybe i'll have the same problems with bpm (big picture mode) .. ?

**Comment by ciaccom** [comment]
Just tried a game and everything is working - it switches automatically to fullscreen (bpm). Kodi version is 17.5

**Comment by blahmutz** [comment]
can you show me your advanced settings from the addon?

**Comment by ciaccom** [comment]
under addon_data/script.steam.launcher/settings.xml:
[code]<settings>
    <setting id="BusyDialogTime" value="15" />
    <setting id="CustomScript" value="false" />
    <setting id="CustomScriptFolder" value="" />
    <setting id="DelUserScript" value="false" />
    <setting id="FilePathCheck" value="true" />
    <setting id="KodiLinux" value="/usr/bin/kodi" />
    <setting id="KodiOsx" value="/Applications/Kodi.app/" />
    <setting id="KodiPortable" value="false" />
    <setting id="KodiWin" value="C:\Program Files (x86)\Kodi\Kodi.exe" />
    <setting id="MinimiseKodi" value="true" />
    <setting id="PostScript" value="" />
    <setting id="PostScriptEnabled" value="false" />
    <setting id="PreScript" value="" />
    <setting id="PreScriptEnabled" value="false" />
    <setting id="QuitKodi" value="1" />
    <setting id="ScriptUpdateCheck" value="true" />
    <setting id="SteamLinux" value="/usr/games/steam" />
    <setting id="SteamOsx" value="/Applications/Steam.app/" />
    <setting id="SteamWin" value="C:\Program Files (x86)\Steam\steam.exe" />
    <setting id="SuspendAudio" value="false" />
    <setting id="WmctrlCheck" value="false" />
</settings>[/code]

**Comment by blahmutz** [comment]
no problem ;) thanks, maybe its because of QuitKodi. I let it only minimize... will try it tomorrow

**Comment by ciaccom** [comment]
MinimizeKodi or QuitKodi does not make any difference here :o/

**Comment by beniwtv** [comment]
Had the same issue with the CRLF on Linux, just reporting here.

**Comment by teeedubb** [comment]
Ugh this issues rears its head again. This file hasn't been updated in 
yonks - I think GitHub changes the line endings based on which OS the files 
were committed from. I'll add some code to the add-on to ensure the line 
endings are correct before the script is run.

**Comment by teeedubb** [comment]
I have updated the addon to automatically correct line endings if running linux. I dont have access to a linux machine much these days, so can you guys please test it? You need to manually install the addon files from my repo (not the zip file) and delete the ~/.kodi/userdata/addon_data/script.steam.launcher/scripts folder.

**Comment by radenling** [comment]
I ran into this problem and tried out the fix on master and everything works nicely.

**Comment by teeedubb** [comment]
Thanks for testing. Ill release a new version, though I have one other change to add for windows due to the update window naming changing, but the pc it is on is temporarily out of action, so Ill do it as soon as I can.

**Comment by teeedubb** [comment]
These changes have been committed to 3.2.3 release.
