### ISSUE TITLE
Steam Launcher doesn't recognize Gnome as a window manager

### ISSUE THREAD

**Issue by billywade** [teeedubb/teeedubb-xbmc-repo#13]
Thanks for making this, I think it'll be really handy once I get it running.

So when I try to run the app, it fails. When debugging's on, I found out I needed ```wmctrl```, so I installed it and restarted. However, it's still telling me that no window manager exists. I'm running the latest Gnome 3, though, so I know I have Mutter installed. What should I do?
```
07:38:48.402 T:139654725891840   DEBUG: CPythonInvoker(24, /home/trey/.kodi/addons/script.steam.launcher/default.py): start processing
07:38:48.479 T:139654725891840   DEBUG: script.steam.launcher: ****Running Steam-Launcher v3.2.3....
07:38:48.479 T:139654725891840   DEBUG: script.steam.launcher: running on osAndroid, osOsx, osLinux, osWin: 0 0 1 0
07:38:48.479 T:139654725891840   DEBUG: script.steam.launcher: System text encoding in use: UTF-8
07:38:48.479 T:139654725891840   DEBUG: script.steam.launcher: usr scripts are set to be checked for updates...
07:38:48.479 T:139654725891840   DEBUG: script.steam.launcher: usr scripts are not set to be deleted, running version check
07:38:48.480 T:139654725891840   DEBUG: script.steam.launcher: sys "steam.launcher.script.revision=": 015
07:38:48.480 T:139654725891840   DEBUG: script.steam.launcher: usr "steam.launcher.script.revision=": 015
07:38:48.480 T:139654725891840   DEBUG: script.steam.launcher: userdata script are up to date
07:38:48.480 T:139654725891840   DEBUG: script.steam.launcher: skipping deleting userdata scripts, option disabled: delUserScriptSett = false
07:38:48.480 T:139654725891840   DEBUG: script.steam.launcher: script file already exists, skipping copy to userdata: /home/trey/.kodi/userdata/addon_data/script.steam.launcher/scripts/steam-launch.sh
07:38:48.492 T:139654725891840   DEBUG: script.steam.launcher: wmctrl present, checking if a window manager is running...
07:38:48.511 T:139654725891840   DEBUG: script.steam.launcher: ERROR: A window manager is NOT running - unless you are using the SteamOS compositor Steam BPM needs a windows manager. If you are using the SteamOS compositor disable the addon option "Check for program wmctrl"
07:38:48.511 T:139654725891840    INFO: CPythonInvoker(24, /home/trey/.kodi/addons/script.steam.launcher/default.py): script aborted
```

**Comment by teeedubb** [comment]
The check I use might not be compatible with gnome. Can you try disabling 
the wmctrl check in the add-ons settings?

**Comment by billywade** [comment]
Works perfectly, thanks. Hey, I have one more thing that's not working: Kodi doesn't recognize Steam as a widget-able add-on. Is that as simple as this is, or should I open a new issue?

**Comment by teeedubb** [comment]
Cool. What do you mean by widget? Like a icon on the home screen to launch 
the add-on?

**Comment by billywade** [comment]
Yeah, with a submenu. It looked like in the screenshots that there was a way to navigate some games via the home screen, but I can't find it in my list of programs in the Titan launcher to make it its own part of the submenu.

**Comment by teeedubb** [comment]
The add-on won't display any lists or launch individual games - it just 
launches steam. I did look at adding this type of functionality to the 
add-on, but I like using the steam bpm interface and its features, so i 
decided not to spent the considerable amount of time to add something I'd 
never use.

Have fun with the add-on

**Comment by billywade** [comment]
Good to know, makes sense. Thanks!

**Comment by billywade** [comment]
I think I figured out what it is anyway. I was trying to launch a fresh instance of Steam, rather than opening the big picture mode of it, and it can't do that. I just have to figure out how to get starting Steam with the ```-silent``` option working for my machine to start it automatically.
