### ISSUE TITLE
Steam opens new friends list window on launch

### ISSUE THREAD

**Issue by pyongyang666** [teeedubb/teeedubb-xbmc-repo#14]
After launching in Big Picture mode, steam then immediately drops back out to desktop when the new friends list appears. Suppressing the list works when launching steam manually with "steam -bigpicture -nochatui -nofriendsui". Any chance of getting your launcher updated to accommodate this?

**Comment by teeedubb** [comment]
Hey mate,

I only just got my PC back recently will add support for custom launch parameters and a few other bits and pieces shortly.

**Comment by teeedubb** [comment]
Added to latest commit
