### ISSUE TITLE
Another spawned instance of kodi when exiting steam

### ISSUE THREAD

**Issue by wberrier** [teeedubb/teeedubb-xbmc-repo#15]
When I exit steam, another kodi instance is started.  It doesn't seem to matter what the setting for "Quit Kodi" is (yes/no/ask), they all seem to behave the same.

Meaning, if I enter/exit steam several times, I end up with several instances of kodi running.

I think I noticed this when upgrading to Kodi 18 (Fedora 29, Kodi 18 rc3).

I verified this on a fresh install of the add-on on a different machine as well.

**Comment by teeedubb** [comment]
Hey mate,

Someone reported this on the forums - it has to do with the Kodi executable being Hamed differently depending on which display manager is being used.
I only recently got my PC PC and installed Ubuntu today so I'll get around to fixing it for Kodi 18 shortly.

**Comment by teeedubb** [comment]
Fixed with latest commit
