### ISSUE TITLE
steam-launcher still complains about python-2.7.19 not found

### ISSUE THREAD

**Issue by hedmo** [teeedubb/teeedubb-xbmc-repo#22]
hi 

i was trying to install the steam-launcher via the zip file  to day here in gentoo 
but getting the error that xbmc does not find python-2.7.19.i am on kodi-19.0_beta1 
and have build it with python 3,7.

regards hedmo

**Comment by teeedubb** [comment]
Have you tried with the steam launcher beta in the forum thread?

Can you provide a Kodi debug log?

**Comment by hedmo** [comment]
> Have you tried with the steam launcher beta in the forum thread?
> 
> Can you provide a Kodi debug log?

I am om to work now . But i Will provide a log for you after. I did try with the one provided here and the One from THE three.

**Comment by hedmo** [comment]
sorry for late reply.i have manage to install it and it was a dependencies problem . do you mind provide me
with the dependencies ? . after the installation i am getting an error message at the top right.as i am working in gentoo i cannot use pip or something like that and need to find know the dependencies and build them in the package manager or i will mess up stuff later on in my system.

**Comment by hedmo** [comment]
i have not manage to provide a kodi.log as i dont understand how that works yet.

**Comment by teeedubb** [comment]
Python dependencies are all contained within kodi. Are you sure you're running the beta for Kodi 19 in the forum thread?

Kodi debug log instructions
https://kodi.wiki/view/Log_file/Easy

**Comment by hedmo** [comment]
i hope this is what you need :
[kodi.log](https://github.com/teeedubb/teeedubb-xbmc-repo/files/5646760/kodi.log)

att the end is the start of script.steam.launcher

**Comment by hedmo** [comment]
here is a new one with wmctrl installed:

[kodi.log](https://github.com/teeedubb/teeedubb-xbmc-repo/files/5646767/kodi.log)

**Comment by hedmo** [comment]
i have manage to start it on one of my boxes by changing line 110 in main.py to : 

if '\r\n' in open(scriptPath,'rb').read(): -> if '\r\n' in open(scriptPath,'r').read():

**Comment by teeedubb** [comment]
Thanks hedmo - that fixed it.

I'll update it today and push it to the repo.
