### ISSUE TITLE
bagelradio

### ISSUE THREAD

**Issue by mechtronsystems** [teeedubb/teeedubb-xbmc-repo#27]
Hi teeedubb,
I've modified your fbi plugin for bagel radio, if you want to include that in the repo can you make a dummy I can fork?  
also, do you know what the icon requirements are for kodi/xbmc, is there a size limit or something?
cheers

**Comment by teeedubb** [comment]
Hey mate,

Yeah happy to host it here if you want, but probably best if you create your own repo as I most likely wont keep it updated. If you need some help let me know. Also best to make a forum post to give it some visibility.

The [Kodi wiki](https://kodi.wiki/view/Add-on_structure#resources/icon.png) states that the maximum addon icon size is 512x512, not sure if you can make them larger
