### ISSUE TITLE
steam-launcher uses wrong locale

### ISSUE THREAD

**Issue by mgrunwald** [teeedubb/teeedubb-xbmc-repo#30]
While my systems default locale is de_DE.UTF-8, the steam launcher uses the locale POSIX. This causes the game Divinity Original Sin to crash with "Failed to create dir" with some saved game in the savegames folder that uses German Umlauts, e.g. "Der Spielplatz des Häuters". 

I can workaround this by adding this line to `.kodi/userdata/addon_data/script.steam.launcher/scripts/steam-launcher.sh` right at the start of the script:

```
export LC_ALL=de_DE.UTF-8
```

I have no Idea why steam-launcher uses the POSIX locale instead of the system default. But this did work before updating the machine to debian 11/bullseye. That version enforced python 3 and removed python 2 - it might be related.

**Comment by teeedubb** [comment]
What does running the command 'locale' output?
On a ubuntu 22.04 system I get:

**LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=**

Just confirming **LC_ALL=** has nothing next to it.
