### ISSUE TITLE
steam.launcher: Not fully functional with new Steam changes

### ISSUE THREAD

**Issue by the0neWhoKnocks** [teeedubb/teeedubb-xbmc-repo#31]
My current Kodi setup will put my system to sleep after X minutes of inactivity. For that reason I have the `steam.launcher` plugin configured with
```
Quit Kodi: Yes
Force kill Kodi after X seconds: 0
```
Otherwise Kodi would put my system to sleep while playing a game.

The problem is that once Steam boots, Kodi no longer closes, and once I close Steam, the script is still running in the system tray.

I checked Kodi's logs to see if there were any errors during the plugin's execution but I didn't see any.

If I update the plugin config to this:
```
Parameters to pass to the Steam executable: -oldbigpicture
```
the plugin works again, but Steam is eventually going to remove that flag.

**Update**:
I see that there's been acknowledgement of this issue finally: https://forum.kodi.tv/showthread.php?tid=157499&page=86, curious if/when any progress will be made on a patch since I originally posted the issue in October.

---

Original beta issue:

> I've opted in to the new Steam beta that allows to test-drive Big Picture with the better SteamOS layout.
>
> The only thing I changed in the plugin config was this addition in Advanced
> ```
> Parameters to pass to the Steam executable: -gamepadui
> ```
> When I remove that flag, things behave as expected again.

**Comment by the0neWhoKnocks** [comment]
Created a patch that works on my system, but I'm sure it'd need a once-over by someone that understands the ins-and-outs of the add-on.
https://github.com/teeedubb/teeedubb-xbmc-repo/compare/master...the0neWhoKnocks:teeedubb-xbmc-repo:fix-31-steamlauncher-malfunctioning?expand=1

**Comment by teeedubb** [comment]
Hey mate,

Nice idea about adding the window groups. I'll check this out soon when I get the time.

Thanks

**Comment by teeedubb** [comment]
Latest addon now works with the new steam bpm ui - thanks for your contribution!

**Comment by the0neWhoKnocks** [comment]
@teeedubb glad I could help out.

Couple things caught my eye:
- Not sure if `txt` files are a requirement for Kodi addons but I saw you kept the README changes and didn't change the `txt` extension to `md`. Also, for maintainability, I just use `1.` for numbered lists so that you can easily move or delete items without having to update the list number since Markdown parsers do that automatically. 
- Looks like you added a `.bak` file, not sure if that was an accidental addition.

**Comment by teeedubb** [comment]
Thanks for the pointers - I've updated the readme.
Yeah I noticed the .bak file after pushing changes to master, it has been removed.
