### ISSUE TITLE
Teeedubb repo not working for Kodi v20

### ISSUE THREAD

**Issue by bickford** [teeedubb/teeedubb-xbmc-repo#33]
Hi @teeedubb ,
Your repository doesn't seem to work for Kodi v20. After installing it from the zip and then trying to access it in Kodi I get the message "Could not connect to repository".

I enabled debugging mode and found these error messages:

`2023-02-09 17:47:51.477 T:14825   error <general>: Repository add-on repository.teeedubb uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.`

`2023-02-09 17:47:51.477 T:14825   error <general>: Repository add-on repository.teeedubb does not have any directory and won't be able to update/serve addons! Please fix the addon.xml definition`

OS: Ubuntu 22.04
Kodi: 20.0.0 (20230115)

Let me know if you'd like me to do any testing/debugging.
Cheers

**Comment by teeedubb** [comment]
Thanks for the issue and log snippet.
Should be fixed now in repository.teeedubb-1.0.3
Please try it and let me know.

**Comment by bickford** [comment]
Hi teeedubb - late response sorry, but yes confirmed working now - thanks again.
